# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hacking Coolpad Note 3
email: abhisek@sigsegv.in
description: > # this means to ignore newlines until "baseurl:"
  Experiments with Coolpad Note 3. From analysis to making it usable.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abhisek.github.io/coolpad_note3/"
twitter_username: abh1sek
github_username:  abhisek
safe: true
lsi: false
github:

# Build settings
markdown: kramdown
